// Copyright (c) 2025-2026, RTE (https://www.rte-france.com)
// This Source Code Form is subject to the terms of the Mozilla Public License, version 2.0.
// If a copy of the Mozilla Public License, version 2.0 was not distributed with this file,
// you can obtain one at http://mozilla.org/MPL/2.0/.
// SPDX-License-Identifier: MPL-2.0
//
// AUTO-GENERATED by scripts/game_mode/matpower/gen_matpower_presets.py. Do not
// edit by hand. The scenario DATA lives in ./matpowerScenarios.json (kept out
// of this source module so it doesn't blow the code-quality line ceiling);
// regenerate both from data/rte_matpower/scenarios.json.
//
// RTE Matpower France EHV game mode: difficulty-graded N-1 scenarios on the
// public MATPOWER RTE cases (case6468/6470/6495/6515rte — real 2013 French EHV
// operating points), rebuilt as NODE_BREAKER so topological levers exist.
// Difficulty is the expert recommender's solvability at the 95% monitoring
// factor:
//   easy   - a suggested unitary action resolves the overloads;
//   medium - no unitary resolves, but a first-identified combination does;
//   hard   - neither a unitary nor a first combination resolves.
// Dates are hidden: titles carry only month + weekday + hour-period, and grids
// live under opaque ids. Non-antenna scenarios only.

import type { GameStudy } from './types';
import { sampleScenarios } from './sampleScenarios';
import scenarios from './matpowerScenarios.json';

export type MatpowerDifficulty = 'easy' | 'medium' | 'hard';

export interface MatpowerTier {
  id: MatpowerDifficulty;
  label: string;
  blurb: string;
  studies: GameStudy[];
}

// The JSON is generated with exactly the GameStudy fields (no nulls), so it is
// structurally a GameStudy[] per level — assign directly, no cast needed.
const BY_DIFFICULTY: Record<MatpowerDifficulty, GameStudy[]> = scenarios;

export const MATPOWER_EASY: GameStudy[] = BY_DIFFICULTY.easy;
export const MATPOWER_MEDIUM: GameStudy[] = BY_DIFFICULTY.medium;
export const MATPOWER_HARD: GameStudy[] = BY_DIFFICULTY.hard;

export const MATPOWER_TIERS: MatpowerTier[] = [
  { id: 'easy',   label: 'Easy — RTE Matpower France EHV',
    blurb: 'A single suggested action clears the overload (expert model, 95% monitoring).',
    studies: MATPOWER_EASY },
  { id: 'medium', label: 'Medium — RTE Matpower France EHV',
    blurb: 'No single action suffices, but a first-identified pair does.',
    studies: MATPOWER_MEDIUM },
  { id: 'hard',   label: 'Hard — RTE Matpower France EHV',
    blurb: 'Neither a single action nor the best estimated pairs resolve it.',
    studies: MATPOWER_HARD },
];

// Deterministic (seedable) draw, round-robin across distinct grids first so a
// small sample spans different operating points.
export function sampleMatpower(
  difficulty: MatpowerDifficulty, n: number, seed?: number,
): GameStudy[] {
  return sampleScenarios(BY_DIFFICULTY[difficulty] ?? [], n, seed);
}
