#!/usr/bin/env python3
# Copyright (c) 2025-2026, RTE (https://www.rte-france.com)
# SPDX-License-Identifier: MPL-2.0
"""Stage 4 of the France RTE Matpower game dataset: generate the frontend
presets from the graded scenario database (``data/rte_matpower/scenarios.json``).

Mirrors ``scripts/game_mode/gen_rte7000_presets.py`` and emits TWO files, for
the same reason: the scenario data must not live inside a source module (the
code-quality gate caps frontend components at 1450 lines).

  - ``frontend/src/game/matpowerScenarios.json`` — player-safe ``GameStudy[]``
    per level; NO reference ``solution`` (that stays server-side) and no date.
  - ``frontend/src/game/matpowerPresets.ts`` — a small module exposing
    ``MATPOWER_TIERS`` and a seedable ``sampleMatpower()`` (the sampler itself
    is shared, in ``./sampleScenarios``).

Run after (re)building scenarios.json:
    python scripts/game_mode/matpower/gen_matpower_presets.py
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
DB = REPO / "data" / "rte_matpower" / "scenarios.json"
GAME_DIR = REPO / "frontend" / "src" / "game"
JSON_OUT = GAME_DIR / "matpowerScenarios.json"
TS_OUT = GAME_DIR / "matpowerPresets.ts"
MONITORING_PCT = 95

TS_MODULE = """// Copyright (c) 2025-2026, RTE (https://www.rte-france.com)
// This Source Code Form is subject to the terms of the Mozilla Public License, version 2.0.
// If a copy of the Mozilla Public License, version 2.0 was not distributed with this file,
// you can obtain one at http://mozilla.org/MPL/2.0/.
// SPDX-License-Identifier: MPL-2.0
//
// AUTO-GENERATED by scripts/game_mode/matpower/gen_matpower_presets.py. Do not
// edit by hand. The scenario DATA lives in ./matpowerScenarios.json (kept out
// of this source module so it doesn't blow the code-quality line ceiling);
// regenerate both from data/rte_matpower/scenarios.json.
//
// RTE Matpower France EHV game mode: difficulty-graded N-1 scenarios on the
// public MATPOWER RTE cases (case6468/6470/6495/6515rte — real 2013 French EHV
// operating points), rebuilt as NODE_BREAKER so topological levers exist.
// Difficulty is the expert recommender's solvability at the 95% monitoring
// factor:
//   easy   - a suggested unitary action resolves the overloads;
//   medium - no unitary resolves, but a first-identified combination does;
//   hard   - neither a unitary nor a first combination resolves.
// Dates are hidden: titles carry only month + weekday + hour-period, and grids
// live under opaque ids. Non-antenna scenarios only.

import type { GameStudy } from './types';
import { sampleScenarios } from './sampleScenarios';
import scenarios from './matpowerScenarios.json';

export type MatpowerDifficulty = 'easy' | 'medium' | 'hard';

export interface MatpowerTier {
  id: MatpowerDifficulty;
  label: string;
  blurb: string;
  studies: GameStudy[];
}

// The JSON is generated with exactly the GameStudy fields (no nulls), so it is
// structurally a GameStudy[] per level — assign directly, no cast needed.
const BY_DIFFICULTY: Record<MatpowerDifficulty, GameStudy[]> = scenarios;

export const MATPOWER_EASY: GameStudy[] = BY_DIFFICULTY.easy;
export const MATPOWER_MEDIUM: GameStudy[] = BY_DIFFICULTY.medium;
export const MATPOWER_HARD: GameStudy[] = BY_DIFFICULTY.hard;

export const MATPOWER_TIERS: MatpowerTier[] = [
  { id: 'easy',   label: 'Easy — RTE Matpower France EHV',
    blurb: 'A single suggested action clears the overload (expert model, 95% monitoring).',
    studies: MATPOWER_EASY },
  { id: 'medium', label: 'Medium — RTE Matpower France EHV',
    blurb: 'No single action suffices, but a first-identified pair does.',
    studies: MATPOWER_MEDIUM },
  { id: 'hard',   label: 'Hard — RTE Matpower France EHV',
    blurb: 'Neither a single action nor the best estimated pairs resolve it.',
    studies: MATPOWER_HARD },
];

// Deterministic (seedable) draw, round-robin across distinct grids first so a
// small sample spans different operating points.
export function sampleMatpower(
  difficulty: MatpowerDifficulty, n: number, seed?: number,
): GameStudy[] {
  return sampleScenarios(BY_DIFFICULTY[difficulty] ?? [], n, seed);
}
"""


def to_study(s: dict) -> dict:
    """The player-facing projection: no `solution`, no date, no grid identity
    beyond the opaque path."""
    return {
        "id": s["id"],
        "label": s["label"],
        "networkPath": s["networkPath"],
        "actionFilePath": s["actionFilePath"],
        "layoutPath": s.get("layoutPath"),
        "contingencyElementId": s["contingencyElementId"],
        "contingencyLabel": s.get("contingencyLabel"),
        "baselineMaxLoadingPct": s.get("baselineMaxLoadingPct"),
        "description": (
            f"{s['title']}. Loss of {s.get('contingencyLabel')} drives a "
            f"worst-case {s.get('baselineMaxLoadingPct')}% line loading. Bring "
            f"every monitored line back under the {MONITORING_PCT}% monitoring "
            f"limit."),
    }


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--db", type=Path, default=DB)
    args = ap.parse_args()
    if not args.db.exists():
        print(f"base introuvable: {args.db}\n"
              "  lancer d'abord scripts/game_mode/matpower/build_scenarios.py")
        return 1
    db = json.loads(args.db.read_text())
    buckets: dict[str, list] = {"easy": [], "medium": [], "hard": []}
    for s in db["scenarios"]:
        if s["difficulty"] in buckets:
            buckets[s["difficulty"]].append(to_study(s))
    JSON_OUT.write_text(json.dumps(buckets, ensure_ascii=False, indent=1))
    TS_OUT.write_text(TS_MODULE)
    print(f"{JSON_OUT} (easy={len(buckets['easy'])} "
          f"medium={len(buckets['medium'])} hard={len(buckets['hard'])})")
    print(f"{TS_OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
