#!/usr/bin/env python3
# Copyright (c) 2025-2026, RTE (https://www.rte-france.com)
# SPDX-License-Identifier: MPL-2.0
"""Generate the France THT game-mode frontend presets from the graded scenario
database (data/rte7000_tht/scenarios.json).

Emits TWO files so the ~7 k lines of scenario data don't live in a source
module (the code-quality gate caps frontend components at 1450 lines):

  - frontend/src/game/rte7000Scenarios.json  -- player-safe GameStudy[] per level
    ({easy,medium,hard}); NO reference `solution` (that stays server-side).
  - frontend/src/game/rte7000Presets.ts      -- a small module that imports the
    JSON and exposes RTE7000_TIERS + a seedable sampleRte7000().

Run after (re)building scenarios.json:
    python3 scripts/game_mode/gen_rte7000_presets.py
"""
import json
import os

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
DB = os.path.join(REPO, "data", "rte7000_tht", "scenarios.json")
GAME_DIR = os.path.join(REPO, "frontend", "src", "game")
JSON_OUT = os.path.join(GAME_DIR, "rte7000Scenarios.json")
TS_OUT = os.path.join(GAME_DIR, "rte7000Presets.ts")

TS_MODULE = """// Copyright (c) 2025-2026, RTE (https://www.rte-france.com)
// SPDX-License-Identifier: MPL-2.0
//
// AUTO-GENERATED by scripts/game_mode/gen_rte7000_presets.py. Do not edit by
// hand. The scenario DATA lives in ./rte7000Scenarios.json (kept out of this
// source module so it doesn't blow the code-quality line ceiling); regenerate
// both from data/rte7000_tht/scenarios.json.
//
// RTE7000 France THT game mode: difficulty-graded N-1 scenarios on reconstructed
// real French THT (>=200 kV) operating points. Difficulty is the expert
// recommender's solvability at the 95% monitoring factor:
//   easy   - a suggested unitary action resolves the overloads;
//   medium - no unitary resolves, but a first-identified combination does;
//   hard   - neither a unitary nor a first combination resolves.
// Dates are hidden: titles carry only month + weekday + hour-period, and grids
// live under opaque ids. Non-antenna scenarios only.

import type { GameStudy } from './types';
import { sampleScenarios } from './sampleScenarios';
import scenarios from './rte7000Scenarios.json';

export type Rte7000Difficulty = 'easy' | 'medium' | 'hard';

export interface Rte7000Tier {
  id: Rte7000Difficulty;
  label: string;
  blurb: string;
  studies: GameStudy[];
}

// The JSON is generated with exactly the GameStudy fields (no nulls), so it is
// structurally a GameStudy[] per level — assign directly, no cast needed.
const BY_DIFFICULTY: Record<Rte7000Difficulty, GameStudy[]> = scenarios;

export const RTE7000_EASY: GameStudy[] = BY_DIFFICULTY.easy;
export const RTE7000_MEDIUM: GameStudy[] = BY_DIFFICULTY.medium;
export const RTE7000_HARD: GameStudy[] = BY_DIFFICULTY.hard;

export const RTE7000_TIERS: Rte7000Tier[] = [
  { id: 'easy',   label: 'Easy — RTE7000 France THT',
    blurb: 'A single suggested action clears the overload (expert model, 95% monitoring).',
    studies: RTE7000_EASY },
  { id: 'medium', label: 'Medium — RTE7000 France THT',
    blurb: 'No single action suffices, but a first-identified pair does.',
    studies: RTE7000_MEDIUM },
  { id: 'hard',   label: 'Hard — RTE7000 France THT',
    blurb: 'Neither a single action nor the best estimated pairs resolve it.',
    studies: RTE7000_HARD },
];

// Deterministic (seedable) draw, round-robin across distinct grids first so a
// small sample spans different operating points. The algorithm is shared with
// the Matpower family — see ./sampleScenarios.
export function sampleRte7000(
  difficulty: Rte7000Difficulty, n: number, seed?: number,
): GameStudy[] {
  return sampleScenarios(BY_DIFFICULTY[difficulty] ?? [], n, seed);
}
"""


def to_study(s):
    return {
        "id": s["id"],
        "label": s["label"],
        "networkPath": s["networkPath"],
        "actionFilePath": s["actionFilePath"],
        "layoutPath": s.get("layoutPath"),
        "contingencyElementId": s["contingencyElementId"],
        "contingencyLabel": s.get("contingencyLabel"),
        "baselineMaxLoadingPct": s.get("baselineMaxLoadingPct"),
        "description": (f"{s['title']}. Loss of {s['contingencyLabel']} drives a worst-case "
                        f"{s.get('baselineMaxLoadingPct')}% line loading. Bring every monitored "
                        f"line back under the 95% monitoring limit."),
    }


def main():
    db = json.load(open(DB, encoding="utf-8"))
    buckets = {"easy": [], "medium": [], "hard": []}
    for s in db["scenarios"]:
        if s["difficulty"] in buckets:
            buckets[s["difficulty"]].append(to_study(s))
    with open(JSON_OUT, "w", encoding="utf-8") as f:
        json.dump(buckets, f, ensure_ascii=False, indent=1)
    with open(TS_OUT, "w", encoding="utf-8") as f:
        f.write(TS_MODULE)
    print(f"wrote {JSON_OUT} (easy={len(buckets['easy'])} medium={len(buckets['medium'])} "
          f"hard={len(buckets['hard'])}) + {TS_OUT}")


if __name__ == "__main__":
    main()
